<nav>
    <ul>
        <li><a href="/projet-final/projet-mairie/espace-famille">Tableau de bord</a></li>
        <li><a href="/projet-final/projet-mairie/espace-famille/<?=  $_SESSION['user_lastName'] ?>/enfants">Mes enfants</a></li>
        <li><a href="/projet-final/projet-mairie/espace-famille/<?= $_SESSION['user_lastName'] ?>/cantine">La Cantine</a></li>
        <li><a href="/projet-final/projet-mairie/authentification/se-deconnecter">Se déconnecter</a></li>
    </ul>
</nav>