<form method="POST" action="/admin/modifier-email">
    <fieldset>
        <label for="email">Préciser votre adresse email actuelle :</label>
        <input type="email" name="email" id="email">
    </fieldset>
    <fieldset>
        <label for="newEmail">Nouvelle adresse email :</label>
        <input type="email" name="newEmail" id="newEmail">
    </fieldset>
    <input type="submit" name="modifyEmail" value="Modifier votre adresse mail">
</form>