<section class="homepage-container">
    <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
    <section class="homepage-shortcutNav-container">
        <h3 class="hidden">Ce titre sera préciser ultérieurement</h3>
        <nav class="shortcutNav">
                <a href="/projet-final/projet-mairie/admin/articles/ajouter">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-city-hall-64.png" alt="">
                    </div>
                    <span class="label">Ajouter une page</span>
                </a>
                <a href="/projet-final/projet-mairie/admin/evenements/ajouter">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-street-sign-64.png" alt="">
                    </div>
                    <span class="label">Ajouter un évènement</span>
                </a>
                <a href="/projet-final/projet-mairie/admin/informations-locales/associations/ajouter">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-contact-64.png" alt="">
                    </div>
                    <span class="label">Ajouter une association</span>
                </a>
                <a href="/projet-final/projet-mairie/admin/informations-locales/professionnels-locaux/ajouter">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-post-office-64.png" alt="">
                    </div>
                    <span class="label">Ajouter un professionnel</span>
                </a>
                <a href="/projet-final/projet-mairie/admin/informations-locales/lieux/ajouter">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-desk-64.png" alt="">
                    </div>
                    <span class="label">Ajouter un lieu</span>
                </a>
                <a href="/projet-final/projet-mairie/admin/ajouter-un-fichier&file=bulletin">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-clipboard-64.png" alt="">
                    </div>
                    <span class="label">Ajouter un bulletin</span>
                </a>
                <a href="/projet-final/projet-mairie/admin/ajouter-un-fichier&file=compte-rendu">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-clipboard-64.png" alt="">
                    </div>
                    <span class="label">Ajouter un compte-rendu</span>
                </a>
                <a href="/projet-final/projet-mairie/admin/cantine">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-clipboard-64.png" alt="">
                    </div>
                    <span class="label">Cantine</span>
                </a>
        </nav>
    </section>
</section>