<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>back-office</h1>
        <!--  add condition if user not connected -> no navigation   -->
        <?php require 'views/partials/admin/_header.phtml'; ?>
    </header>

    <main>
        <?php require $this->template; ?>
    </main>

    <footer>
        <?php require 'views/partials/admin/_footer.phtml'; ?>
    </footer>
</body>
</html>

