<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mairie de Saint-Broladre</title>
</head>
<body>
<header>
    <h1>layout</h1>
    <?php require 'views/partials/admin/_header.phtml'; ?>
</header>

<main>
    <?php require $this->template; ?>
    <?php //var_dump($_SESSION['user_id']); var_dump($_SESSION['user_role']); ?>

</main>

<footer>
    <?php require 'views/partials/admin/_footer.phtml'; ?>
</footer>
<script type="module" src="/projet-final/projet-mairie/assets/js/index.js"></script>
</body>
</html>