<form action="index.php?route/admin/informations-locales/professionnels-locaux/ajouter">
    <fieldset><label for=""></label><input type="text" name=""></fieldset>
    <fieldset><label for=""></label><input type="text" name=""></fieldset>
    <fieldset><label for=""></label><input type="text" name=""></fieldset>
    <fieldset><label for=""></label><input type="text" name=""></fieldset>
    <fieldset>
        <label for="address">Adresse postal :</label>
        <input type="text" name="address">
    </fieldset>
    <fieldset>
        <label for="code-postal">Code postal :</label>
        <input type="text" name="code-postal" required>
    </fieldset>
    <fieldset>
        <label for="ville">Ville/Commune :</label>
        <input type="text" name="ville" required>
    </fieldset>
    <input type="submit" name="registerLocalProfessional" value="Enregistrer nouveau professionnel">
</form>