<form method="POST" action="/admin/informations-locales/professionnels-locaux/ajouter">
    <fieldset>
        <label for="name">nom entreprise</label>
        <input type="text" name="name" required>
    </fieldset>
    <fieldset>
        <label for="sector">secteur</label>
        <input type="text" name="sector">
    </fieldset>
    <fieldset>
        <label for="firstname">prénom ceo</label>
        <input type="text" name="firstname">
    </fieldset>
    <fieldset>
        <label for="lastname">nom ceo</label>
        <input type="text" name="lastname" required>
    </fieldset>
    <fieldset>
        <label for="address">Adresse postal :</label>
        <input type="text" name="address">
    </fieldset>
    <fieldset>
        <label for="code-postal">Code postal :</label>
        <input type="text" name="code-postal" required>
    </fieldset>
    <fieldset>
        <label for="ville">Ville/Commune :</label>
        <input type="text" name="ville" required>
    </fieldset>
    <input type="submit" name="registerLocalProfessional" value="Enregistrer nouveau professionnel">
</form>