<form method="POST" action="/projet-final/projet-mairie/admin/evenements/ajouter">
    <fieldset>
        <label for="title">Nom de l'évènement : </label>
        <input type="text" name="title" id="title" required>
    </fieldset>
    <fieldset>
        <label for="description">Description</label>
        <input type="text" name="description" id="description">
    </fieldset>
    <fieldset>
        <label for="date">Date : </label>
        <input type="date" name="date" id="date" required>
    </fieldset>
    <fieldset>
        <label for="address">Adresse postal :</label>
        <input type="text" name="address" id="address">
    </fieldset>
    <fieldset>
        <label for="code-postal">Code postal :</label>
        <input type="text" name="code-postal" id="code-postal" required>
    </fieldset>
    <fieldset>
        <label for="ville">Ville/Commune :</label>
        <input type="text" name="ville" id="ville" required>
    </fieldset>
    <input type="submit" name="registerEvent" value="Enregistrer l'évènement">
</form>