<?php
$events = $this->data['events'];
?>
<section class="main-container">
    <h1><?= $this->pageTitle ?></h1>
    
    <section class="table-container">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <a href="/projet-final/projet-mairie/admin/evenements/ajouter">Ajouter un évènement</a>
        
        <table>
            <thead>
            <tr>
                <th>Nom de l'évènement</th>
                <th>Date</th>
                <th>Description</th>
                <th>Adresse</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($events as $event)
            {
                $rp = new ReflectionProperty('Event', 'address');
                ?>
                <tr>
                    <td> <?= $event->getTitle(); ?> </td>
                    <td> <?= $event->getDate()->format('d/m/Y'); ?> </td>
                    <td> <?= $event->getDescription(); ?> </td>
                    <td> <?php
                        if ($rp->isInitialized($event)){
                            echo $event->getAddress()->getAddress().', '.$event->getAddress()->getCodePostal().' '.$event->getAddress()->getCommune();
                        } else {
                            echo 'Pas d\'adresse spécifiée pour cet évènement';
                        }
                        ?>
                    </td>
                    <td><a href="/projet-final/projet-mairie/admin/evenements/modifier&eventId=<?= $event->getId(); ?>">Modifier</a></td>
                </tr>
                <?php
            }
            ?>
            </tbody>
        </table>
    </section>
    
</section>