<nav>
    <ul>
        <li><a href="/">Accueil</a></li>
        <li><a href="/mairie">Mairie</a></li>
        <li><a href="/projets">Projets en cours</a></li>
        <li><a href="/pratique">Pratique</a></li>
        <li><a href="/vivre">Vivre à Saint-Broladre</a></li>
        <li><a href="/decouvrir">Découvrir</a></li>
        <li><a href="/espace-famille">Espace Famille</a></li>
        <li><a href="/mentions-legales">Mentions Légales</a></li>
        <li><a href="/politique-confidentialite">Politique de confidentialité</a></li>
    </ul>
</nav>