<nav>
    <ul>
        <li><a href="/projet-final/projet-mairie/">Accueil</a></li>
        <li><a href="/projet-final/projet-mairie/mairie">Mairie</a></li>
        <li><a href="/projet-final/projet-mairie/pratique">Pratique</a></li>
        <li><a href="/projet-final/projet-mairie/vivre">Vivre à Saint-Broladre</a></li>
        <li><a href="/projet-final/projet-mairie/espace-famille">Espace Famille</a></li>
        <li><a href="/projet-final/projet-mairie/mentions-legales">Mentions Légales</a></li>
        <li><a href="/projet-final/projet-mairie/politique-confidentialite">Politique de confidentialité</a></li>
    </ul>
</nav>