<nav>
    <ul>
        <li><a href="/projet-mairie/admin">back-office</a></li>
        <li><a href="/projet-mairie/mairie">mairie</a></li>
        <li><a href="/projet-mairie/projets">projets</a></li>
        <li><a href="/projet-mairie/pratique">pratique</a></li>
        <li><a href="/projet-mairie/vivre">vivre</a></li>
        <li><a href="/projet-mairie/decouvrir">decouvrir</a></li>
        <li><a href="/projet-mairie/espace-famille">espace famille</a></li>
    </ul>
</nav>