<nav id="mainNav">
    <ul>
        <li><a href="/admin">Back-0ffice</a></li>
        <li><a href="/">Accueil</a></li>
        <li><a href="/mairie">Mairie</a></li>
        <li><a href="/projets">Projets en cours</a></li>
        <li><a href="/pratique">Pratique</a></li>
        <li><a href="/vivre">Vivre à Saint-Broladre</a></li>
        <li><a href="/decouvrir">Découvrir</a></li>
        <li><a href="/espace-famille">Espace Famille</a></li>
    </ul>
</nav>