<nav id="mainNav">
    <ul>
        <li><a href="/projet-final/projet-mairie/">Accueil</a></li>
        <li><a href="/projet-final/projet-mairie/projets">Projets en cours</a></li>
        <li><a href="/projet-final/projet-mairie/mairie">Mairie</a></li>
        <li><a href="/projet-final/projet-mairie/pratique">Vie Pratique</a></li>
        <li><a href="/projet-final/projet-mairie/vivre">Vivre à Saint-Broladre</a></li>
        <li><a href="mailto:peltierblanche@gmail.com">Nous contacter</a></li>
        <li><a href="/projet-final/projet-mairie/espace-famille">Espace Famille</a></li>
    </ul>
</nav>