<form method="post" action="/authentification/se-connecter">
    <fieldset>
        <label for="email">Adresse mail :</label>
        <input type="email" name="email" required>
    </fieldset>
    <fieldset>
        <label for="password">Mot de passe :</label>
        <input type="password" name="password" required>
    </fieldset>
    <input type="submit" name="login" value="Se connecter"/>
</form>