<section class="main-container">
    <h1><?= $this->pageTitle ?></h1>
    
    <section class="form-container">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <form method="POST" action="/projet-final/projet-mairie/admin/informations-locales/associations/modifier&associationId=<?= $_GET['associationId'] ?>">
            <fieldset>
                <label for="name">Nom de l'association :</label>
                <input type="text" name="name" id="name" required>
            </fieldset>
            <fieldset>
                <label for="presidentFirstname">Prénom du·de la président·e :</label>
                <input type="text" name="presidentFirstname" id="presidentFirstname">
            </fieldset>
            <fieldset>
                <label for="presidentLastname">Nom du·de la président·e :</label>
                <input type="text" name="presidentLastname" id="presidentLastname" required>
            </fieldset>
            <fieldset>
                <legend>Status : </legend>
                <label for="active">Active (default)</label>
                <input type="radio" name="status" value="active" id="active" checked>
                <label for="archived">Archived</label>
                <input type="radio" name="status" value="archived" id="archived">
            </fieldset>
            <fieldset>
                <label for="address">Adresse postale (ex: 1 rue Dupont)</label>
                <input type="text" name="address" id="address">
            </fieldset>
            <fieldset>
                <label for="code-postal">Code postal :</label>
                <input type="text" name="code-postal" id="code-postal" required>
            </fieldset>
            <fieldset>
                <label for="ville">Ville/Commune :</label>
                <input type="text" name="ville" id="ville" required>
            </fieldset>
            <input id="submit" type="submit" name="modifyAssociation" value="Enregistrer l'association modifiée">
        </form>
    </section>
</section>