<form method="POST" action="/admin/informations-locales/associations/modifier&associationId=<?= $_GET['associationId'] ?>">
    <fieldset>
        <label for="name">Nom de l'association</label>
        <input type="text" name="name">
    </fieldset>
    <fieldset>
        <label for="presidentFirstname">Prénom du président/de la présidente de l'association</label>
        <input type="text" name="presidentFirstname">
    </fieldset>
    <fieldset>
        <label for="presidentLastname">Nom du président/de la présidente de l'association</label>
        <input type="text" name="presidentLastname">
    </fieldset>
    <fieldset>
        <legend>Status : </legend>
        <label for="active">Active (default)
            <input type="radio" name="status" value="active" checked></label>
        <label for="archived">Archived
            <input type="radio" name="status" value="archived"></label>
    </fieldset>
    <fieldset>
        <label for="address">Adresse postal :</label>
        <input type="text" name="address">
    </fieldset>
    <fieldset>
        <label for="code-postal">Code postal :</label>
        <input type="text" name="code-postal">
    </fieldset>
    <fieldset>
        <label for="ville">Ville/Commune :</label>
        <input type="text" name="ville">
    </fieldset>
    <input type="submit" name="modifyAssociation" value="Enregistrer l'association modifiée">
</form>