<form method="POST" action="/projet-final/projet-mairie/admin/informations-locales/associations/modifier&associationId=<?= $_GET['associationId'] ?>">
    <fieldset>
        <label for="name">Nom de l'association</label>
        <input type="text" name="name" id="name" required>
    </fieldset>
    <fieldset>
        <label for="presidentFirstname">Prénom du président/de la présidente de l'association</label>
        <input type="text" name="presidentFirstname" id="presidentFirstname">
    </fieldset>
    <fieldset>
        <label for="presidentLastname">Nom du président/de la présidente de l'association</label>
        <input type="text" name="presidentLastname" id="presidentLastname" required>
    </fieldset>
    <fieldset>
        <legend>Status : </legend>
        <label for="active">Active (default)</label>
        <input type="radio" name="status" value="active" id="active" checked>
        <label for="archived">Archived</label>
        <input type="radio" name="status" value="archived" id="archived">
    </fieldset>
    <fieldset>
        <label for="address">Adresse postal :</label>
        <input type="text" name="address" id="address">
    </fieldset>
    <fieldset>
        <label for="code-postal">Code postal :</label>
        <input type="text" name="code-postal" id="code-postal" required>
    </fieldset>
    <fieldset>
        <label for="ville">Ville/Commune :</label>
        <input type="text" name="ville" id="ville" required>
    </fieldset>
    <input type="submit" name="modifyAssociation" value="Enregistrer l'association modifiée">
</form>