<?php
$associations = $this->data['associations'];
?>
<section class="main-container">
    <h1><?= $this->pageTitle ?></h1>
    
    <section class="table-container">
        <a href="/projet-final/projet-mairie/admin/informations-locales/associations/ajouter">Ajouter une association</a>
        
        <table>
            <thead>
            <tr>
                <th>Nom de l'association</th>
                <th>Nom et prénom du·de la président·e</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach($associations as $association)
            {
                ?>
                <tr>
                    <td> <?= $association->getName(); ?> </td>
                    <td> <?= $association->getPresidentLastName() . ' ' .$association->getPresidentFirstName(); ?> </td>
                    <td><a href="/projet-final/projet-mairie/admin/informations-locales/associations/modifier&associationId=<?= $association->getId(); ?>">Modifier</a></td>
                </tr>
            <?php
            }
            ?>
            </tbody>
        </table>
    </section>
    
</section>