<main class="container grid">
    <h1 class="element-card">Accueil</h1>
    <section class="element-card main_header">
        <section class="posts-list">
            <section class="post-card">
                <h2>Article 1</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, consequatur, nihil magnam dolore perferendis vitae saepe et distinctio fuga placeat veritatis error voluptate sed necessitatibus. Rem ex nihil asperiores deserunt?</p>
            </section>
            <section class="post-card">
                <h2>Article 1</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, consequatur, nihil magnam dolore perferendis vitae saepe et distinctio fuga placeat veritatis error voluptate sed necessitatibus. Rem ex nihil asperiores deserunt?</p>
            </section>
            <section class="post-card">
                <h2>Article 1</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, consequatur, nihil magnam dolore perferendis vitae saepe et distinctio fuga placeat veritatis error voluptate sed necessitatibus. Rem ex nihil asperiores deserunt?</p>
            </section>
            <section class="post-card">
                <h2>Article 1</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, consequatur, nihil magnam dolore perferendis vitae saepe et distinctio fuga placeat veritatis error voluptate sed necessitatibus. Rem ex nihil asperiores deserunt?</p>
            </section>
            <section class="post-card">
                <h2>Article 1</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit, consequatur, nihil magnam dolore perferendis vitae saepe et distinctio fuga placeat veritatis error voluptate sed necessitatibus. Rem ex nihil asperiores deserunt?</p>
            </section>
        </section>
    </section>
    <aside class="element-card main_aside">
        <h2>Évènements</h2>
        <ul>
            <li>Lorem ipsum, dolor sit amet consectetur adipisicing.</li>
            <li>Autem sint inventore aliquid itaque, ullam corporis.</li>
            <li>Sequi quaerat quae culpa maiores ea ducimus.</li>
            <li>Repellendus id officia delectus, quo iusto natus?</li>
            <li>Repellendus voluptatem ullam nisi fugiat ipsam consectetur.</li>
        </ul>
    </aside>
    <section class="element-card main_contact-form">
        <h2>Nous contacter</h2>
        <form method="POST" action="index.php?"> <!-- ajouter bonne route -->
            <fieldset><label for="firstname">Nom</label><input type="text" name="firstname" id="firstname" placeholder="Dupont"></fieldset>
            <fieldset><label for="lastname">Prénom</label><input type="text" name="lastname" id="lastname" placeholder="Jean"></fieldset>
            <fieldset><label for="email">Adresse email</label><input type="email" name="email" id="email" placeholder="dupontjean@hotmail.com"></fieldset>
            <fieldset>
                <label for="type_of_demand">Nature de la demande </label>
                <select name="type_of_demand" id="type_of_demand">
                    <option value="urbanisme">Urbanisme</option>
                    <option value="rendez-vous">Demande de prise de rendez-vous</option>
                    <option value="etat-civil">Etat civil</option>
                    <option value="infos">Informations</option>
                    <option value="voirie">Voirie</option>
                </select>
            </fieldset>
            <textarea name="" id="" cols="30" rows="10" placeholder="Votre demande..."></textarea>
            <input type="submit" value="Valider la demande">
        </form>
    </section>
    <section class="element-card main_image">
        <!-- <img src="/assets/images/cropped-anne.jpg" alt=""> -->
    </section>
    <section class="element-card main_social-links"> 
        <h2>Social Links</h2>
        <ul>
            <li>
                <a href=""><i class="fa-brands fa-instagram fa-lg"></i>Instagram</a>
            </li>
            <li>
                <a href=""><i class="fa-brands fa-facebook-f fa-lg"></i>Facebook</a>
            </li>
            <li>
                <a href=""><img class="main_social-link_img" src="/assets/images/120px-Logo_IntraMuros.png" alt="" srcset="">Intramuros</a>
            </li>
        </ul>
    </section>
    <section class="element-card main_horaires"> 
        <h2>Horaires</h2>
        <dl>
            <dt>Mairie</dt>
            <dd>Lundi</dd>
            <dd>Mardi</dd>
            <dd>Mercredi</dd>
            <dd>Jeudi</dd>
            <dd>Vendredi</dd>
            <dd>Week-end</dd>
        </dl>
        <dl>
            <dt>Poste</dt>
            <dd>Lundi</dd>
            <dd>Mardi</dd>
            <dd>Mercredi</dd>
            <dd>Jeudi</dd>
            <dd>Vendredi</dd>
            <dd>Week-end</dd>
        </dl>
    </section>
</main>