<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mairie de Saint-Broladre</title>
</head>
<body>
    <header>
        <h1>layout</h1>
        <?php require 'partials/public/_header.phtml'; ?>
    </header>

    <main>
        <?php require $this->template; ?>
        <?php
            if ((!isset($_GET['route'])) || ((isset($_GET['route']) && $_GET['route'] !== 'login')))
            {
                ?>
                <section class="element-card main_contact-form">
                    <h2>Nous contacter</h2>
                    <?php require '_contact-form.phtml'; ?>
                </section>
                <?php
            }
        ?>
    </main>

    <footer>
        <?php require 'partials/public/_footer.phtml'; ?>
    </footer>
</body>
</html>