<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mairie de Saint-Broladre</title>
</head>
<body>
    <header>
        <h1>layout</h1>
        <?php require 'partials/public/_header.phtml'; ?>
    </header>

    <?php
        /*$users = $this->data['users'];
        var_dump($users);
        echo '</br>';
        foreach ($users as $user)
            foreach ($user as $data)
            {
                echo $data.'</br>';

            }
        {
        }
        echo '</br>';
        $user = $users[0];
        echo $user['email'];*/
    ?>
    <main>
        <?php require $this->template; ?>
        <section class="element-card main_contact-form">
            <h2>Nous contacter</h2>
            <form method="POST" action="index.php?"> <!-- ajouter bonne route -->
                <fieldset><label for="firstname">Nom</label><input type="text" name="firstname" id="firstname" placeholder="Dupont"></fieldset>
                <fieldset><label for="lastname">Prénom</label><input type="text" name="lastname" id="lastname" placeholder="Jean"></fieldset>
                <fieldset><label for="email">Adresse email</label><input type="email" name="email" id="email" placeholder="dupontjean@hotmail.com"></fieldset>
                <fieldset>
                    <label for="type_of_demand">Nature de la demande </label>
                    <select name="type_of_demand" id="type_of_demand">
                        <option value="urbanisme">Urbanisme</option>
                        <option value="rendez-vous">Demande de prise de rendez-vous</option>
                        <option value="etat-civil">Etat civil</option>
                        <option value="infos">Informations</option>
                        <option value="voirie">Voirie</option>
                    </select>
                </fieldset>
                <textarea name="" id="" cols="30" rows="10" placeholder="Votre demande..."></textarea>
                <input type="submit" value="Valider la demande">
            </form>
        </section>
    </main>

    <footer>
        <?php require 'partials/public/_footer.phtml'; ?>
    </footer>
</body>
</html>