<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mairie de Saint-Broladre</title>
</head>
<body>
    <header>
        <h1>layout</h1>
        <?php require 'partials/public/_header.phtml'; ?>
    </header>

    <?php
        /*$users = $this->data['users'];
        var_dump($users);
        echo '</br>';
        foreach ($users as $user)
            foreach ($user as $data)
            {
                echo $data.'</br>';

            }
        {
        }
        echo '</br>';
        $user = $users[0];
        echo $user['email'];*/
    ?>
    <main>
        <?php require $this->template; ?>
    </main>

    <footer>
        <?php require 'partials/public/_footer.phtml'; ?>
    </footer>
</body>
</html>