<section class="main-container">    
    <h1> <?= $this->pageTitle; ?> </h1>
    <section class="sub-pages-list">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <a href="/projet-final/projet-mairie/pratique/agence-postale">Agence Postale Communale</a>
        <a href="/projet-final/projet-mairie/mairie/services-municipaux">Services Municipaux</a>
    </section>
</section>