<header>
        <section class="container header">
            <section>
                <h1 >Mairie de Saint-Broladre</h1>
                <p>Commune de la baie du Mont-Saint-Michel</p>
            </section>
            <nav>
                <ul>
                    <li><a href="#" class="homepage-link">Accueil</a></li>
                    <li><a href="#">Mairie</a></li>
                    <li><a href="#">Projets en cours</a></li>
                    <li><a href="#">Pratique</a></li>
                    <li><a href="#">Vivre</a></li>
                    <li><a href="#">Découvrir</a></li>
                    <li><a href="#" class="espace_famille">Espace Famille</a></li>
                </ul>
            </nav>
        </section>
    </header>