<section class="main-container">
    <h1><?= $this->pageTitle ?></h1>
    
    <section class="form-container">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <form method="POST" action="/projet-final/projet-mairie/espace-famille/<?= $_SESSION['user_lastName']; ?>/enfants/modifier/<?= $this->data['childId'];?>">
            <fieldset>
                <label for="firstName">Prénom : </label>
                <input type="text" name="firstName">
            </fieldset>
            <fieldset>
                <label for="lastName">Nom de famille : </label>
                <input type="text" name="lastName">
            </fieldset>
            <fieldset>
                <label for="age">Age : </label>
                <input type="number" name="age">
            </fieldset>
            <input id="submit" type="submit" name="modifiyChild" value="Enregistrer les modifications">
        </form>
    </section>
</section>