<section class="main-container">
    <h1><?= $this->pageTitle ?></h1>
    
    <section class="form-container">
        <form method="POST" action="/projet-final/projet-mairie/espace-famille/<?= $_SESSION['user_lastName'] ?>/ajouter">
            <fieldset>
                <label for="firstName">Prénom :</label>
                <input type="text" name="firstName">
            </fieldset>
            <fieldset>
                <label for="lastName">Nom de famille :</label>
                <input type="text" name="lastName">
            </fieldset>
            <fieldset>
                <label for="age">Age : </label>
                <input type="number" name="age">
            </fieldset>
            <input id="submit" type="submit" name="add-child" value="Enregistrer mon enfant">
        </form>
    </section>
</section>