<?php
$week = $this->data['week'];
$children = $this->data['children'];
?>
<section class="main-container">
    <h1> <?= $this->pageTitle; ?> </h1>
    <section class="form-container">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <form method="POST" action="/projet-final/projet-mairie/espace-famille/<?= $_SESSION['user_lastName'] ?>/cantine/inscrire/<?= $week->getWeekOfYear(); ?>">
            <fieldset>
                <label for="enfant">Choississez quel enfant inscrire</label>
                <select name="enfant" id="enfant">
                <?php foreach($children as $child)
                {
                    ?>
                        <option value="<?= $child->getId(); ?>">
                            <?= $child->getFirstName(); ?>
                        </option>
                    <?php
                }
                ?>
                </select>
            </fieldset>
            <section class="table-container">
                <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
                <table>
                    <thead>
                    <tr>
                        <th>Monday</th>
                        <th>Tuesday</th>
                        <th>Wednesday</th>
                        <th>Thursday</th>
                        <th>Friday</th>
                    </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td> <?= checkStatus($week->getMonday(), 'form', 'monday'); ?>
                            </td>
                            <td> <?= checkStatus($week->getTuesday(), 'form', 'tuesday'); ?>
                            </td>
                            <td> <?= checkStatus($week->getWednesday(), 'form', 'wednesday'); ?>
                            </td>
                            <td> <?= checkStatus($week->getThursday(), 'form', 'thursday'); ?>
                            </td>
                            <td> <?= checkStatus($week->getFriday(), 'form', 'friday'); ?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </section>
            <input id="submit" type="submit" name="enrollChild" value="Inscrire l'enfant">
        </form>
    </section>
</section>