<?php
$week = $this->data['week'];
$children = $this->data['children'];
?>
<h1> <?= $this->pageTitle; ?> </h1>cantine semaine <?= $_GET['semaine']?></h1>
<form method="POST" action="index.php?route=espace-famille/cantine/modifier-semaine&semaine=<?= $week->getWeekOfYear(); ?>" onsubmit="beforeSubmit()">
    <fieldset>
        <label for="enfant">Choississez quel enfant inscrire</label>
        <select name="enfant" id="enfant">
        <?php foreach($children as $child)
        {
            ?>
                <option value="<?= $child->getId(); ?>">
                    <?= $child->getFirstName(); ?>
                </option>
            <?php
        }
        ?>
        </select>
    </fieldset>
    <table>
        <thead>
        <tr>
            <th>Monday</th>
            <th>Tuesday</th>
            <th>Wednesday</th>
            <th>Thursday</th>
            <th>Friday</th>
        </tr>
        </thead>
        <tbody>
            <tr>
                <td> <?php
                    if($week->getMonday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getMonday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getMonday() === "Holiday")
                    {
                        ?>
                        <fieldset>
                            <label for="monday">(Vacances/Férié)</label>
                            <input type="checkbox" name="mondayPlacebo" value="Holiday" checked disabled>
                            <input type="hidden" value="Holiday" name="monday">
                        </fieldset>
                        <?php
                    }
                    else
                    {
                        ?>
                        <fieldset>
                            <label for="monday"></label>
                            <input type="checkbox" name="monday" value="Yes">
                        </fieldset>
                        <?php
                    }
                    ?>
                </td>
                <td> <?php
                    if($week->getTuesday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getTuesday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getTuesday() === "Holiday")
                    {
                        ?>
                        <fieldset>
                            <label for="tuesday">(Vacances/Férié)</label>
                            <input type="checkbox" name="tuesdayPlacebo" value="Holiday" checked disabled>
                            <input type="hidden" value="Holiday" name="tuesday">
                        </fieldset>
                        <?php
                    }
                    else
                    {
                        ?>
                        <fieldset>
                            <label for="tuesday"></label>
                            <input type="checkbox" name="tuesday" value="Yes">
                        </fieldset>
                        <?php
                    }
                    ?>
                </td>
                <td> <?php
                    if($week->getWednesday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getWednesday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getWednesday() === "Holiday")
                    {
                        ?>
                        <fieldset>
                            <label for="wednesday">(Vacances/Férié)</label>
                            <input type="checkbox" name="wednesdayPlacebo" value="Holiday" checked disabled>
                            <input type="hidden" value="Holiday" name="wednesday">
                        </fieldset>
                        <?php
                    }
                    else
                    {
                        ?>
                        <fieldset>
                            <label for="wednesday"></label>
                            <input type="checkbox" name="wednesday" value="Yes">
                        </fieldset>
                        <?php
                    }
                    ?>
                </td>
                <td> <?php
                    if($week->getThursday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getThursday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getThursday() === "Holiday")
                    {
                        ?>
                        <fieldset>
                            <label for="thursday">(Vacances/Férié)</label>
                            <input type="checkbox" name="thursdayPlacebo" value="Holiday" checked disabled>
                            <input type="hidden" value="Holiday" name="thursday">
                        </fieldset>
                        <?php
                    }
                    else
                    {
                        ?>
                        <fieldset>
                            <label for="thursday"></label>
                            <input type="checkbox" name="thursday" value="Yes">
                        </fieldset>
                        <?php
                    }
                    ?>
                </td>
                <td> <?php
                    if($week->getFriday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getFriday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getFriday() === "Holiday")
                    {
                        //echo '☀️';
                        ?>
                        <fieldset>
                            <label for="friday">(Vacances/Férié)</label>
                            <input type="checkbox" name="fridayPlacebo" value="Holiday" checked disabled="disabled" id="friday">
                            <input type="hidden" value="Holiday" name="friday">
                        </fieldset>
                        <?php
                    }
                    else
                    {
                        ?>
                        <fieldset>
                            <label for="friday"></label>
                            <input type="checkbox" name="friday" value="Yes">
                        </fieldset>
                        <?php
                    }
                    ?>
                </td>
            </tr>
        </tbody>
    </table>
    <input type="submit" value="Inscrire l'enfant">
</form>