<?php
$weeks = $this->data['cafeteria-weeks'];
$children = $this->data['children'];
$childrenEnrollments = $this->data['childrenEnrollments'];
?>
<h1>cantine</h1>
<table>
    <thead>
    <tr>
        <th>Week</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
        <th>Actions</th>
        <th>Enfants</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($childrenEnrollments as $childEnrollment)
    {
    $foundMatch = false;
        //var_dump($childEnrollment);
        //echo '<br>';
        $firstName = $childEnrollment[0];
        //var_dump($firstName);
        //echo '<br>';
        $enrollments = $childEnrollment[1];
        //var_dump($enrollments);
        //echo '<br>';

        foreach ($enrollments as $item)
        {
            foreach ($weeks as $week)
            {
            if (!$foundMatch && $week->getWeekOfYear() === $item->getWeekOfYear())
            {
                //$foundMatch = true;
                //echo $week->getWeekOfYear().' '.$item->getWeekOfYear().'<br>';
                //echo $firstName.' registered for '.$week->getWeekOfYear();

                $data = $item;
                ?>
                <tr>

                    <td> <?= $data->getWeekOfYear(); ?></td>
                    <!--have another td that takes all td with days inside of it inside a table and tr element-->
                    <td> <?php
                        if($data->getMonday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getMonday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getMonday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td> <?php
                        if($data->getTuesday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getTuesday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getTuesday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td> <?php
                        if($data->getWednesday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getWednesday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getWednesday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td> <?php
                        if($data->getThursday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getThursday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getThursday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td> <?php
                        if($data->getFriday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getFriday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getFriday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td><a href="index.php?route=espace-famille/cantine/modifier-semaine&semaine=<?= $data->getWeekOfYear(); ?>">Modifier</a></td>
                    <td> <?= $firstName ?> </td>
                </tr>
                <?php
            }
            else
            {
                //echo $week->getWeekOfYear().' '.$item->getWeekOfYear().'<br>';
                //echo $firstName.' not registered for '.$week->getWeekOfYear();
                $data = $week;
                ?>
                <tr>

                    <td> Base <?= $data->getWeekOfYear(); ?></td>
                    <td> <?php
                        if($data->getMonday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getMonday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getMonday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td> <?php
                        if($data->getTuesday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getTuesday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getTuesday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td> <?php
                        if($data->getWednesday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getWednesday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getWednesday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td> <?php
                        if($data->getThursday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getThursday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getThursday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td> <?php
                        if($data->getFriday() === "Yes")
                        {
                            echo '✅';
                        }
                        else if ($data->getFriday() === "No")
                        {
                            echo '❌';
                        }
                        else if ($data->getFriday() === "Holiday")
                        {
                            echo '☀️';
                        }
                        else
                        {
                            echo 'à préciser';
                        }
                        ?>
                    </td>
                    <td><a href="index.php?route=espace-famille/cantine/modifier-semaine&semaine=<?= $data->getWeekOfYear(); ?>">Modifier</a></td>
                    <td> <?= $firstName ?> </td>
                </tr>
                <?php
                }
            }
        }
    }
    ?>

    </tbody>
</table>

<?php
    foreach ($this->data['childrenEnrollments'] as $childEnrollments)
    {
        $firstName = $childEnrollments[0];
        foreach ($childEnrollments[1] as $enrollment)
        {
            //echo $firstName;
            //echo $enrollment->getWeekOfYear();
        }
    }
?>

<table>
    <thead>
    <tr>
        <th>Week</th>
        <th>Monday</th>
        <th>Tuesday</th>
        <th>Wednesday</th>
        <th>Thursday</th>
        <th>Friday</th>
        <th>Actions</th>
        <th>Enfants</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($weeks as $week)
    {
        foreach ($this->data['childrenEnrollments'] as $childEnrollments)
        {
            $firstName = $childEnrollments[0];
            foreach ($childEnrollments[1] as $enrollment)
            {
                //echo $firstName;
                //echo $enrollment->getWeekOfYear();

                if ($week->getWeekOfYear() === $enrollment->getWeekOfyear())
                {

        ?>
        <tr>
            <td> <?= $week->getWeekOfYear(); ?></td>
            <td>

            </td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><a href="#">modifier</a></td>
            <td></td>
        </tr>
        <?php
                }
            }
        }
    }
    ?>
    </tbody>
</table>