<?php
$weeks = $this->data['cafeteria-weeks'];
$children = $this->data['children'];
?>
<h1>cantine</h1>
<?php
foreach ($weeks as $week)
{
?>
<ul>
    <li>
        <?= $week->getWeekOfYear(); ?>
    </li>
</ul>
    <table>
        <thead>
        <tr>
            <th>Week</th>
            <th>Monday</th>
            <th>Tuesday</th>
            <th>Wednesday</th>
            <th>Thursday</th>
            <th>Friday</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($weeks as $week)
        {
            ?>
            <tr>

                <td> <?= $week->getWeekOfYear(); ?></td>
                <td> <?php
                    if($week->getMonday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getMonday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getMonday() === "Holiday")
                    {
                        echo '☀️';
                    }
                    else
                    {
                        echo 'à préciser';
                    }
                    ?>
                </td>
                <td> <?php
                    if($week->getTuesday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getTuesday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getTuesday() === "Holiday")
                    {
                        echo '☀️';
                    }
                    else
                    {
                        echo 'à préciser';
                    }
                    ?>
                </td>
                <td> <?php
                    if($week->getWednesday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getWednesday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getWednesday() === "Holiday")
                    {
                        echo '☀️';
                    }
                    else
                    {
                        echo 'à préciser';
                    }
                    ?>
                </td>
                <td> <?php
                    if($week->getThursday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getThursday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getThursday() === "Holiday")
                    {
                        echo '☀️';
                    }
                    else
                    {
                        echo 'à préciser';
                    }
                    ?>
                </td>
                <td> <?php
                    if($week->getFriday() === "Yes")
                    {
                        echo '✅';
                    }
                    else if ($week->getFriday() === "No")
                    {
                        echo '❌';
                    }
                    else if ($week->getFriday() === "Holiday")
                    {
                        echo '☀️';
                    }
                    else
                    {
                        echo 'à préciser';
                    }
                    ?>
                </td>
                <td><a href="index.php?route=espace-famille/cantine/modifier-semaine&semaine=<?= $week->getWeekOfYear(); ?>">Modifier</a></td>
            </tr>
          <?php
        }?>

        </tbody>
    </table>
<?php
}
?>
