<section class="homepage-container">
    
    <section class="homepage-image-container">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <img src="/projet-final/projet-mairie/assets/images/cropped-anne-1568x427.jpg" alt="Bannière du site - Photo de la Chapelle de Saint-Anne, située sur la commune de Saint-Broladre">
    </section>
        
    <section class="homepage-shortcutNav-container">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <nav class="shortcutNav">
                <a href="/projet-final/projet-mairie/espace-famille/<?=  $_SESSION['user_lastName'] ?>/enfants">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-city-hall-64.png" alt="">
                    </div>
                    <span class="label">Mes Enfants</span>
                </a>
                <a href="/projet-final/projet-mairie/espace-famille/<?= $_SESSION['user_lastName'] ?>/cantine">
                    <div class="svg-container">
                        <img src="/projet-final/projet-mairie/assets/images/homepage-shortcutNav-icons/icons8-street-sign-64.png" alt="">
                    </div>
                    <span class="label">La Cantine</span>
                </a>
        </nav>
    </section>
</section>