<p>Liste de vos enfants : </p>
<ul>
    <?php
    $children = $this->data['children'];
    foreach($children as $child)
    {
    ?>
        <li> <?= $child->getFirstName(); ?>
            <a href="index.php?route=espace-famille/consulter-enfant&enfantId=<?= $child->getId(); ?>">Consulter</a>
        </li>
    <?php
    }
    ?>

</ul>
<a href="index.php?route=espace-famille/ajouter-enfant">ajouter enfant</a>