<p>Liste de vos enfants : </p>
<ul>
    <?php
    $children = $this->data['children'];
    foreach($children as $child)
    {
    ?>
        <li> <?= $child->getFirstName(); ?>
            <a href="/projet-final/projet-mairie/espace-famille/<?= $_SESSION['user_lastName'] ?>/enfants/<?= $child->getId(); ?>">Consulter</a>
        </li>
    <?php
    }
    ?>

</ul>
<a href="/projet-final/projet-mairie/espace-famille/<?= $_SESSION['user_lastName'] ?>/enfants/ajouter">ajouter enfant</a>