<section class="main-container">
    <h1> <?= $this->pageTitle; ?> </h1>
    <a class="main-container-link" href="/projet-final/projet-mairie/espace-famille/<?= $_SESSION['user_lastName'] ?>/enfants/ajouter">Ajouter mon enfant</a>
    
    <section class="list-items">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <article>
            <h3 class="hidden">Ce titre sera préciser ultérieurement</h3>
            <ul>
                <?php
                $children = $this->data['children'];
                foreach($children as $child)
                {
                ?>
                    <li> <?= $child->getFirstName(); ?>
                        <a href="/projet-final/projet-mairie/espace-famille/<?= $_SESSION['user_lastName'] ?>/enfants/<?= $child->getId(); ?>">Consulter</a>
                    </li>
                <?php
                }
                ?>
            
            </ul>
        </article>
    </section>
</section>