<main class="container grid">
    <h1 class="element-card">Titre</h1>
    <section class="element-card main_header">
        <h2>Titre</h2>
    </section>
    <aside class="element-card main_aside">
        <h2>Titre</h2>
    </aside>
    <section class="element-card main_contact-form">
        <h2>Titre</h2>
    </section>
    <section class="element-card main_image">
        <h2>Titre</h2>
    </section>
    <section class="element-card main_social-links">
        <h2>Titre</h2>
    </section>
    <section class="element-card main_horaire">
        <h2>Titre</h2>
    </section>
</main>