<h1> <?= $this->pageTitle; ?> </h1>
<nav>
    <ul>
        <li><a href="/projet-final/projet-mairie/admin/informations-locales/associations">associations</a></li>
        <li><a href="/projet-final/projet-mairie/admin/informations-locales/professionnels-locaux">professionnels-locaux</a></li>
        <li><a href="/projet-final/projet-mairie/admin/informations-locales/lieux">lieux</a></li>
    </ul>
</nav>