<section class="main-container">    
    <h1> <?= $this->pageTitle; ?> </h1>
    <section class="sub-pages-list">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
         <a href="/projet-final/projet-mairie/admin/informations-locales/associations">Associations</a> 
         <a href="/projet-final/projet-mairie/admin/informations-locales/professionnels-locaux">Professionnels Locaux</a> 
         <a href="/projet-final/projet-mairie/admin/informations-locales/lieux">Lieux</a> 
    </section>
</section>