<h1> <?= $this->pageTitle; ?> </h1>
<form method="POST" action="/admin/cantine/nouvelle-annee">
    <fieldset>
        <label for="year-start">year start</label>
        <input type="date" name="year-start">
    </fieldset>
    <fieldset>
        <label for="year-end">year end</label>
        <input type="date" name="year-end">
    </fieldset>
    <input type="submit" name="createNewYear" value="Générer la nouvelle année scolaire">
</form>