<section class="main-container">
    <h1><?= $this->pageTitle ?></h1>
    
    <section class="form-container">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <form method="POST" action="">
            <fieldset>
                <label for="name">Nom de l'association</label>
                <input type="text" name="name" id="name" required>
            </fieldset>
            <input id="submit" type="submit" name="" value="">
        </form>
    </section>
</section>