<?php
$weeks = $this->data['cafeteria-weeks'];
//var_dump($weeks);
?>
<h1> <?= $this->pageTitle; ?> </h1>cantine</h1>
<a href="/admin/cantine/creer-annee-scolaire">générer semaine pour nouvelle année scolaire</a>
<form method="POST" action="/admin/cantine/exporter">
    <input type="submit" value="Exporter" name="exportCafeteriaWeeks">
    <table>
        <thead>
            <tr>
                <th>Week</th>
                <th>Monday</th>
                <th>Tuesday</th>
                <th>Wednesday</th>
                <th>Thursday</th>
                <th>Friday</th>
                <th>Selectionner les semaines à exporter</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach ($weeks as $week)
        {
        ?>
            <tr>
                <td> <?= $week->getWeekOfYear(); ?> </td>
                <td> <?php checkStatus($week->getMonday()); ?></td>
                <td> <?php checkStatus($week->getTuesday()); ?></td>
                <td> <?php checkStatus($week->getWednesday()); ?></td>
                <td> <?php checkStatus($week->getThursday()); ?> </td>
                <td> <?php checkStatus($week->getFriday()); ?> </td>
                <td>
                    <fieldset>
                        <label for="<?= $week->getWeekOfYear(); ?>"></label>
                        <input type="checkbox" name="weekNumber[]" value="<?= $week->getWeekOfYear(); ?>">
                    </fieldset>
                </td>
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
</form>