<?php
$weeks = $this->data['cafeteria-weeks'];
//var_dump($weeks);
?>
<section class="main-container">
    <h1> <?= $this->pageTitle; ?> </h1>
    <a class="main-container-link" href="/projet-final/projet-mairie/admin/cantine/creer-annee-scolaire">générer semaine pour nouvelle année scolaire</a>
    
    <section class="form-container">
        
        <form method="POST" action="/projet-final/projet-mairie/admin/cantine/exporter">
            <input id="submit" type="submit" value="Exporter" name="exportCafeteriaWeeks">
        
            <section class="table-container">
                <table>
                    <thead>
                        <tr>
                            <th>Week</th>
                            <th>Monday</th>
                            <th>Tuesday</th>
                            <th>Wednesday</th>
                            <th>Thursday</th>
                            <th>Friday</th>
                            <th>Selectionner les semaines à exporter</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($weeks as $week)
                    {
                    ?>
                        <tr>
                            <td> <?= $week->getWeekOfYear(); ?> </td>
                            <td> <?php checkStatus($week->getMonday(), '', 'monday'); ?></td>
                            <td> <?php checkStatus($week->getTuesday(), '', 'tuesday'); ?></td>
                            <td> <?php checkStatus($week->getWednesday(), '', 'wednesday'); ?></td>
                            <td> <?php checkStatus($week->getThursday(), '', 'thursday'); ?> </td>
                            <td> <?php checkStatus($week->getFriday(), '', 'friday'); ?> </td>
                            <td>
                                <fieldset>
                                    <label for="<?= $week->getWeekOfYear(); ?>"></label>
                                    <input type="checkbox" name="weekNumber[]" value="<?= $week->getWeekOfYear(); ?>">
                                </fieldset>
                            </td>
                        </tr>
                    <?php
                    }
                    ?>
                    </tbody>
                </table>
                
            </section>
        </form>
        
    </section>
</section>