<form enctype="multipart/form-data" method="post" action="index.php?route=admin/ajouter-un-fichier&file=bulletin">
    <input type="hidden" name="formName" value="uploadBM">
    <input type="hidden" name="MAX_FILE_SIZE" value="3000000" />
    <fieldset>
        <label for="bulletin">Choisir votre fichier</label>
        <input type="file" name="bulletin">
    </fieldset>
    <input type="submit" name="uploadBM" value="Send File" />
</form>