<h1> <?= $this->pageTitle; ?> </h1>bulletins municipaux</h1>
<a href="index.php?route=admin/ajouter-un-fichier&file=bulletin">Ajouter un BM</a>
<ul>
    <?php
    $files = $this->data['bulletins'];

    foreach($files as $file)
    {
    ?>
        <li>
            <?php echo 'Bulletin du '.substr($file['date'], 0, -8);?> <a target="_blank" href="<?=$file['url']?>">Consulter le fichier</a>
        </li>
    <?php
    }
    ?>
</ul>