<h1> <?= $this->pageTitle; ?> </h1>bulletins municipaux</h1>
<a href="/projet-final/projet-mairie/admin/ajouter-un-fichier&file=bulletin">Ajouter un BM</a>
<ul>
    <?php
    $files = $this->data['bulletins'];

    foreach($files as $file)
    {
    ?>
        <li>
            <?php echo 'Bulletin du '.$file->getDate()->format('d/m/Y');?> <a target="_blank" href="<?=$file->getUrl()?>">Consulter le fichier</a>
        </li>
    <?php
    }
    ?>
</ul>