<section class="main-container">
    <h1> <?= $this->pageTitle; ?> </h1>
    
    <section class="sub-pages-list">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <a href="/projet-final/projet-mairie/mairie/services-municipaux/recensement">Recensement</a>
        <a href="/projet-final/projet-mairie/mairie/services-municipaux/papiers-identite">Papiers d'identité</a>
        <a href="/projet-final/projet-mairie/mairie/services-municipaux/location-salle">Louer une salle</a>
    </section>
</section>