<?php
$locations = $this->data['locations'];
?>
<h1><?= $this->pageTitle ?> </h1>
<a href="index.php?route=admin/informations-locales/lieux/ajouter">add location</a>
<table>
    <thead>
    <tr>
        <th>Nom du lieu</th>
        <th>Type</th>
        <th>telephone</th>
        <th>description</th>
        <th>actions</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($locations as $location)
    {
        ?>
        <tr>
            <td> <?= $location->getName(); ?> </td>
            <td> <?= $location->getType(); ?> </td>
            <td> <?= $location->getTelephone(); ?></td>
            <td> <?= $location->getDescription(); ?></td>
            <td><a href="index.php?route=admin/informations-locales/lieux/modifier&locationId=<?= $location->getId(); ?>">modifier location</a></td>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>