<section class="main-container">
    <h1> <?= $this->pageTitle; ?> </h1>
    
    <section class="list-items">
        <article>
            <?php
            $bulletins = $this->data['bulletins'];
            ?>
            <ul>
                <?php
            foreach ($bulletins as $bulletin)
            {
                ?>
                <li> <?php echo 'Bulletin du '.$bulletin->getDate()->format('d/m/Y');?> <a target="_blank" href="<?=$bulletin->getUrl()?>">Consulter le fichier</a>
                </li>
            <?php
            }
            ?>
            </ul>
        </article>
    </section>
</section>
