<section class="main-container">
    <h1> <?= $this->pageTitle; ?> </h1>
    
    <section class="list-items">
        <article>
            <?php
            $crcms = $this->data['comptes-rendus'];
            ?>
            <ul>
            <?php
            foreach ($crcms as $crcm)
            {
                ?>
                <li> <?php echo 'Bulletin du '.$crcm->getDate()->format('d/m/Y');?> <a target="_blank" href="<?=$crcm->getUrl()?>">Consulter le fichier</a>
                </li>
                <?php
            }
            ?>
            </ul>
        </article>
    </section>
</section>

