<h1> <?= $this->pageTitle; ?> </h1>conseil municipal</h1>
<a href="/projet-final/projet-mairie/mairie/conseil-municipal/elus">elus</a>
<a href="/projet-final/projet-mairie/mairie/conseil-municipal/plu">plu</a>
<section>
    <h1>comptes rendus cm</h1>
    <?php
    $crcms = $this->data['crcm'];
    ?>
    <ul>
        <?php
        foreach ($crcms as $crcm)
        {
            ?>
            <li> <?php echo 'Bulletin du '.$crcm->getDate()->format('d/m/Y');?> <a target="_blank" href="<?=$crcm->getUrl()?>">Consulter le fichier</a>
            </li>
            <?php
        }
        ?>
    </ul>
    <a href="/projet-final/projet-mairie/mairie/conseil-municipal/crcm">Voir tous les crcm</a>
</section>
<section>
    <h1>bulletins municpaux</h1>
    <?php
    $bulletins = $this->data['bm'];
    ?>
    <ul>
        <?php
        foreach ($bulletins as $bulletin)
        {
            ?>
            <li> <?php echo 'Compte rendu du '.$bulletin->getDate()->format('d/m/Y');?> <a target="_blank" href="<?=$bulletin->getUrl()?>">Consulter le fichier</a>
            </li>
            <?php
        }
        ?>
    </ul>
    <a href="/projet-final/projet-mairie/mairie/conseil-municipal/bm">Voir tous les bm</a>
</section>