<?php 
//get page info
$content = $this->data['content'];
$picture = $this->data['picture'];
?>
<h1> <?= $this->pageTitle; ?> </h1>


<?php 
//for page with sub pages
?>
<?php foreach($pages as $page){
?>
<a href="#">
    <?php if($page->getPicture() !== null) {
        ?>
    <section class="image-container">
        <h2 class="hidden">Ce titre sera préciser ultérieurement</h2>
        <img src="<?= $page->getPicture()->getUrl() ?>">
    </section>
        <?php
    }?>
    <span class="label"> <?= $page->getTitle() ?></span>
</a>
<?php } 
?>