<?php
$events = $this->data['events'];
?>
<h1> <?= $this->pageTitle; ?> </h1>
<aside class="element-card main_aside">
    <h2>Évènements</h2>
    <ul>
        <?php
        foreach($events as $event)
        {
            $rp = new ReflectionProperty('Event', 'address');
        ?>
            <li>
                <?= $event->getTitle(); ?>
                <ul>
                    <li>
                        <?= $event->getDate()->format('d/m/Y'); ?>
                    </li>
                    <li>
                        <?= $event->getDescription(); ?>
                    </li>
                    <li>
                        <?php
                        if ($rp->isInitialized($event)){
                            echo $event->getAddress()->getAddress().', '.$event->getAddress()->getCodePostal().' '.$event->getAddress()->getCommune();
                        } else {
                            echo 'Pas d\'adresse spécifiée pour cet évènement';
                        }
                        ?>
                    </li>
                </ul>
            </li>
        <?php
        }
        ?>
    </ul>
</aside>