<h1>comtpes rendus cm</h1>
<a href="index.php?route=admin/ajouter-un-fichier&file=compte-rendu">Ajouter un CRCM</a>
<ul>
    <?php
    $files = $this->data['comptes-rendus'];

    foreach($files as $file)
    {
        ?>
        <li>
            <?php echo 'Compte rendu du '.substr($file['date'], 0, -8);?> <a target="_blank" href="<?=$file['url']?>">Consulter le fichier</a>
        </li>
        <?php
    }
    ?>
</ul>