<section class="main-container">
    <h1> <?= $this->pageTitle; ?> </h1>
    <a class="main-container-link" href="/projet-final/projet-mairie/admin/ajouter-un-fichier&file=compte-rendu">Ajouter un compte-rendu</a>
    
    <section class="list-items">
        <article>
            <h3>Derniers comptes-rendus :</h3>
            <ul>
                <?php
                $files = $this->data['comptes-rendus'];
                $counter = 0;
                foreach($files as $file)
                {
                    if($counter < 45) {
                    ?>
                    <li>
                        <?php echo 'Compte rendu du '.$file->getDate()->format('d/m/Y');?> <a target="_blank" href="<?=$file->getUrl()?>">Consulter le fichier</a>
                    </li>
                    <?php
                        
                    } else {
                        break;
                    }
                    $counter++;
                }
                ?>
            </ul>
        </article>
    </section>
</section>