<h1> <?= $this->pageTitle; ?> </h1>
<a href="/projet-final/projet-mairie/admin/ajouter-un-fichier&file=compte-rendu">Ajouter un CRCM</a>
<ul>
    <?php
    $files = $this->data['comptes-rendus'];

    foreach($files as $file)
    {
        ?>
        <li>
            <?php echo 'Compte rendu du '.$file->getDate()->format('d/m/Y');?> <a target="_blank" href="<?=$file->getUrl()?>">Consulter le fichier</a>
        </li>
        <?php
    }
    ?>
</ul>