<nav>
    <ul>
        <li><a href="/admin/">Tableau de bord</a></li>
        <li><a href="/admin/articles">Les Articles</a></li>
        <li><a href="/admin/projets">Les Projets</a></li>
        <li><a href="/admin/evenements"> Les Evènements</a></li>
        <li><a href="/admin/informations-locales">Les Informations Locales</a></li> <!-- add dropdown menu with each type of infos -->
        <li><a href="/admin/cantine">La Cantine</a></li>
        <li><a href="/admin/bulletins-municipaux">Les Bulletins Municipaux</a></li>
        <li><a href="/admin/comptes-rendus-conseils-municipaux">Les Comptes-rendus des Conseils Municipaux</a></li>
        <li><a href="/admin/modifier-email">Modifer mon adresse email</a></li>
        <li><a href="/authentification/se-deconnecter">Se déconnecter</a></li>
    </ul>
</nav>