<nav>
    <ul>
        <li><a href="index.php?route=articles">articles</a></li>
        <li><a href="index.php?route=projets">projets</a></li>
        <li><a href="index.php?route=events">evenements</a></li>
        <li><a href="index.php?route=cantine">cantine</a></li>
        <li><a href="index.php?route=bulletins-municipaux">bulletins-municipaux</a></li>
        <li><a href="index.php?route=comptes-rendus-conseils-municipaux">comptes-rendus-conseils-municipaux</a></li>
        <li><a href="index.php?route=logout">logout</a></li>
    </ul>
</nav>