<nav>
    <ul>
        <li><a href="index.php?route=admin/articles">articles</a></li>
        <li><a href="index.php?route=admin/projets">projets</a></li>
        <li><a href="index.php?route=admin/events">evenements</a></li>
        <li><a href="index.php?route=admin/cantine">cantine</a></li>
        <li><a href="index.php?route=admin/bulletins-municipaux">bulletins-municipaux</a></li>
        <li><a href="index.php?route=admin/comptes-rendus-conseils-municipaux">comptes-rendus-conseils-municipaux</a></li>
        <li><a href="index.php?route=logout">logout</a></li>
    </ul>
</nav>