<nav>
    <ul>
        <li><a href="/admin/">Dashboard</a></li>
        <li><a href="/admin/articles">articles</a></li>
        <li><a href="/admin/projets">projets</a></li>
        <li><a href="/admin/events">evenements</a></li>
        <li><a href="/admin/informations-locales">informations locales</a></li> <!-- add dropdown menu with each type of infos -->
        <li><a href="/admin/cantine">cantine</a></li>
        <li><a href="/admin/bulletins-municipaux">bulletins-municipaux</a></li>
        <li><a href="/admin/comptes-rendus-conseils-municipaux">comptes-rendus-conseils-municipaux</a></li>
        <li><a href="/authentification/se-deconnecter">logout</a></li>
    </ul>
</nav>